import { RoseType, WrapperStyle } from '@/types/bouquet';

export const ROSES: RoseType[] = [
  {
    id: 'red',
    name: 'Red Rose',
    color: '#C0392B',
    gradientFrom: '#E74C3C',
    gradientTo: '#922B21',
    category: 'Love',
    meaningEn: 'Passionate love, romance, deep affection',
    meaningKo: '열정적인 사랑, 로맨스, 깊은 애정',
    image: '/assets/roses/red.png',
  },
  {
    id: 'pink',
    name: 'Pink Rose',
    color: '#E91E8C',
    gradientFrom: '#F48FB1',
    gradientTo: '#C2185B',
    category: 'Love',
    meaningEn: 'Admiration, sweetness, gentle affection',
    meaningKo: '감탄, 다정함, 부드러운 애정',
    image: '/assets/roses/pink.png',
  },
  {
    id: 'white',
    name: 'White Rose',
    color: '#ECF0F1',
    gradientFrom: '#FFFFFF',
    gradientTo: '#BDC3C7',
    category: 'Memory',
    meaningEn: 'Purity, sincerity, new beginning',
    meaningKo: '순수함, 진심, 새로운 시작',
    image: '/assets/roses/white.png',
  },
  {
    id: 'yellow',
    name: 'Yellow Rose',
    color: '#F1C40F',
    gradientFrom: '#F9E44B',
    gradientTo: '#D4AC0D',
    category: 'Friendship',
    meaningEn: 'Friendship, joy, warm wishes',
    meaningKo: '우정, 기쁨, 따뜻한 응원',
    image: '/assets/roses/yellow.png',
  },
  {
    id: 'orange',
    name: 'Orange Rose',
    color: '#E67E22',
    gradientFrom: '#F39C12',
    gradientTo: '#CA6F1E',
    category: 'Friendship',
    meaningEn: 'Enthusiasm, desire, vibrant energy',
    meaningKo: '열정, 설렘, 생기 있는 에너지',
    image: '/assets/roses/orange.png',
  },
  {
    id: 'lavender',
    name: 'Lavender Rose',
    color: '#9B59B6',
    gradientFrom: '#D7BDE2',
    gradientTo: '#7D3C98',
    category: 'Love',
    meaningEn: 'Enchantment, mystery, love at first sight',
    meaningKo: '매혹, 신비로움, 첫눈에 반한 마음',
    image: '/assets/roses/lavender.png',
  },
  {
    id: 'blue',
    name: 'Blue Rose',
    color: '#2980B9',
    gradientFrom: '#85C1E9',
    gradientTo: '#1A5276',
    category: 'Memory',
    meaningEn: 'Impossible dream, mystery, uniqueness',
    meaningKo: '이루기 어려운 꿈, 신비, 특별함',
    image: '/assets/roses/blue.png',
  },
  {
    id: 'black',
    name: 'Black Rose',
    color: '#1C1C1C',
    gradientFrom: '#555555',
    gradientTo: '#000000',
    category: 'Apology',
    meaningEn: 'Farewell, transformation, deep memory',
    meaningKo: '이별, 변화, 깊은 기억',
    image: '/assets/roses/black.png',
  },
  {
    id: 'peach',
    name: 'Peach Rose',
    color: '#E8A87C',
    gradientFrom: '#FDEBD0',
    gradientTo: '#CA6F1E',
    category: 'Gratitude',
    meaningEn: 'Gratitude, sincerity, appreciation',
    meaningKo: '감사, 진심, 고마움',
    image: '/assets/roses/peach.png',
  },
];

export const CATEGORIES = ['All', 'Love', 'Friendship', 'Gratitude', 'Apology', 'Memory'] as const;
export type CategoryFilter = typeof CATEGORIES[number];

export const WRAPPERS: WrapperStyle[] = [
  { id: 'pink',     name: 'Pink',     nameKo: '핑크',   paperColor: '#F2C4CE', paperDark: '#C8809A', ribbonColor: '#C0607C' },
  { id: 'black',    name: 'Black',    nameKo: '블랙',   paperColor: '#2E2E2E', paperDark: '#1A1A1A', ribbonColor: '#808080' },
  { id: 'white',    name: 'White',    nameKo: '화이트', paperColor: '#F0EDE8', paperDark: '#C8C4BE', ribbonColor: '#A8A4A0' },
  { id: 'beige',    name: 'Beige',    nameKo: '베이지', paperColor: '#E8DEC8', paperDark: '#C0A878', ribbonColor: '#A08858' },
  { id: 'burgundy', name: 'Burgundy', nameKo: '버건디', paperColor: '#6B1F2E', paperDark: '#3E1018', ribbonColor: '#9B3048' },
];

export const DEFAULT_WRAPPER_ID = 'pink';
